In [46]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn import metrics

In [2]:
df = pd.read_csv('final_features.csv')

In [12]:
df.columns
df.head()

,Unnamed: 0,date,start_station_id,start_hour,size,start_station_name,city,zip_code,mean_temperature_f,mean_humidity,...,18,19,20,21,22,23,94041,94063,94107,95113
0,0,2013-08-29,3,13,1,San Jose Civic Center,San Jose,95113,72.0,69.0,...,0,0,0,0,0,0,0,0,0,1
1,1,2013-08-29,3,18,1,San Jose Civic Center,San Jose,95113,72.0,69.0,...,1,0,0,0,0,0,0,0,0,1
2,2,2013-08-29,3,20,1,San Jose Civic Center,San Jose,95113,72.0,69.0,...,0,0,1,0,0,0,0,0,0,1
3,3,2013-08-29,3,21,2,San Jose Civic Center,San Jose,95113,72.0,69.0,...,0,0,0,1,0,0,0,0,0,1
4,4,2013-08-29,3,22,4,San Jose Civic Center,San Jose,95113,72.0,69.0,...,0,0,0,0,1,0,0,0,0,1

In [14]:
df = df.rename(columns={'size': 'count'})
df.head()

,Unnamed: 0,date,start_station_id,start_hour,count,start_station_name,city,zip_code,mean_temperature_f,mean_humidity,...,18,19,20,21,22,23,94041,94063,94107,95113
0,0,2013-08-29,3,13,1,San Jose Civic Center,San Jose,95113,72.0,69.0,...,0,0,0,0,0,0,0,0,0,1
1,1,2013-08-29,3,18,1,San Jose Civic Center,San Jose,95113,72.0,69.0,...,1,0,0,0,0,0,0,0,0,1
2,2,2013-08-29,3,20,1,San Jose Civic Center,San Jose,95113,72.0,69.0,...,0,0,1,0,0,0,0,0,0,1
3,3,2013-08-29,3,21,2,San Jose Civic Center,San Jose,95113,72.0,69.0,...,0,0,0,1,0,0,0,0,0,1
4,4,2013-08-29,3,22,4,San Jose Civic Center,San Jose,95113,72.0,69.0,...,0,0,0,0,1,0,0,0,0,1

In [70]:
df.columns

Index(['Unnamed: 0', 'date', 'start_station_id', 'start_hour', 'count',
       'start_station_name', 'city', 'zip_code', 'mean_temperature_f',
       'mean_humidity', 'mean_visibility_miles', 'mean_wind_speed_mph',
       'precipitation_inches', 'weekday', 'isHoliday', 'isRushHour', 'Friday',
       'Monday', 'Saturday', 'Sunday', 'Thursday', 'Tuesday', 'Wednesday', '0',
       '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13',
       '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '94041',
       '94063', '94107', '95113'],
      dtype='object')

In [68]:
df_final = df.dropna()

def lin_reg(feature_cols):
    X = df_final[feature_cols]
    y = df_final["count"]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
    linreg = LinearRegression()
    linreg.fit(X_train, y_train) # Fit model to training data
    linreg.predict(X_train) 
    y_pred = linreg.predict(X_test) # X_test predictions
    print("\ny-pred:")
    print(y_pred)
    # Prints y-intercept 
    print("\ny-intercept:")
    print(linreg.intercept_)
    # Prints the beta coefficients in same order as passed
    print("\nCoefficients in same order as passed:")
    print(linreg.coef_)
    # Zip can pair feature names and coefficients together
    zip(feature_cols, linreg.coef_)
    
    # prints result of MAE
    print("\nMAE:")
    print(metrics.mean_absolute_error(y_test, y_pred))
    # prints result of MSE
    print("\nMSE:")
    print(metrics.mean_squared_error(y_test, y_pred))
    # prtins result of RMSE 
    print("\nRMSE:")
    print(np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

In [75]:
feature_cols = ["mean_humidity", "mean_visibility_miles", "precipitation_inches"]
lin_reg(feature_cols)

y-pred:
[2.69748134 2.82680855 2.86991762 ... 2.76214495 2.99924484 2.89147216]

y-intercept:
1.4053760152665542

Coefficients in same order as passed:
[ 0.02155454  0.00419423 -0.52917649]

MAE:
2.2813227541147096

MSE:
16.717997847515015

RMSE:
4.088764831524921

In [76]:
feature_cols = ['start_hour', 'zip_code', 'mean_temperature_f',
       'mean_humidity', 'mean_visibility_miles', 'mean_wind_speed_mph',
       'precipitation_inches', 'isHoliday', 'isRushHour', 'Friday',
       'Monday', 'Saturday', 'Sunday', 'Thursday', 'Tuesday', 'Wednesday']
lin_reg(feature_cols)

y-pred:
[2.89840357 2.89549002 1.45480555 ... 1.0173021  3.61004612 3.6184508 ]

y-intercept:
140.5527237581106

Coefficients in same order as passed:
[-1.02637802e-01 -1.44772706e-03 -1.13627780e-02  2.79840512e-03
 -1.47110022e-01  1.36682179e-01 -1.42962512e+00 -4.84463943e-01
  1.87438262e+00  1.44070548e-01  3.51501744e-01 -7.62035374e-01
 -8.27864704e-01  3.34365465e-01  3.67167452e-01  3.92794869e-01]

MAE:
2.1535418245675824

MSE:
14.387318990854956

RMSE:
3.793061954523674

In [77]:
feature_cols = ['start_hour', 'zip_code', 'isHoliday', 'isRushHour', 'Friday',
       'Monday', 'Saturday', 'Sunday', 'Thursday', 'Tuesday', 'Wednesday']
lin_reg(feature_cols)

y-pred:
[3.64012672 2.9046302  1.5160636  ... 0.77134423 3.84398934 3.84398934]

y-intercept:
157.9908424704842

Coefficients in same order as passed:
[-1.01931310e-01 -1.64302020e-03 -6.27698918e-01  1.82626054e+00
  1.74102015e-01  3.75948982e-01 -7.33832688e-01 -8.36483791e-01
  2.77489071e-01  3.87045725e-01  3.55730685e-01]

MAE:
2.168058372992692

MSE:
14.626594181218968

RMSE:
3.8244730592879024